### ISSUE TITLE
Accent Color

### ISSUE THREAD

**Issue by CallMeEchoCodes** [catppuccin/prismlauncher#1]
It appears the default accent color here is blue. a script to change it to other accent colors would be really nice

**Comment by Mqisty** [comment]
What do you mean by accent color? Do you mean the highlighted color? 

Could you possibly attach a screenshot?

**Comment by CallMeEchoCodes** [comment]
![image](https://user-images.githubusercontent.com/36752347/200986392-cfe72bb1-5cf0-4dd0-a48e-ed2d8c25745a.png)
as you can see blue is used as a highlight. in other ctp ports you can change the color of your main accent

**Comment by Mqisty** [comment]
I'd have to learn how to make a script but it shouldn't be that hard. You'll have to give me a little though since I have school and other things.

**Comment by kokkermanz** [comment]
You can change it by modifying the theme.json. You will need to change `"Highlight"` to whatever color you prefer.

**Comment by Mqisty** [comment]
Clearly I'm never going to make this script so I just added another part to the FAQ in case others want to change the color.
